### ISSUE TITLE
switch config format from json to toml

### ISSUE THREAD

**Issue by moiSentineL** [moiSentineL/flomo#88]
`json` is dead. `toml` is the new meta.

```json
{
    "default_session_data": {
        "tag": "work",
        "name": "Working",
        "ratio": 5
    },
    "notification_priority": "normal",
    "tag_colors": {
        "work": "red",
        "study": "blue",
        "exercise": "green",
        "coding": "aquamarine3",
        "video": "aquamarine3"
    }
}
```

vs

```toml
[defaults]
tag = 'work'
name = 'working'
divisor = 5

[notifications]
priority = 'Normal'
sound = 'path/to/file'

[tags]
work = "red"
study = "blue"
exercise =  "green"
coding =  "aquamarine3"
video = "aquamarine3"
```

_clean._

https://realpython.com/python-toml/#use-toml-as-a-configuration-format
